from __future__ import annotations

from typing import Any, Final

# This stub is derived from symbols exported in src/starlink/ast/Ast.c.
# Method signatures are inferred from PyArg_ParseTuple* format strings.

__version__: str
_C_API: Any

# Constants exported from ICONST/DCONST/CCONST macros
XMLNS: Final[str]
AU: Final[float]
BAD: Final[float]
C: Final[float]
DD2R: Final[float]
DPI: Final[float]
DPIBY2: Final[float]
DR2D: Final[float]
H: Final[float]
NAN: Final[float]
NANF: Final[float]
SOLRAD: Final[float]
AIR: Final[int]
AIT: Final[int]
ALLFRAMES: Final[int]
AND: Final[int]
ANY: Final[int]
ARC: Final[int]
AZP: Final[int]
BADTYPE: Final[int]
BADTS: Final[int]
BASE: Final[int]
BEPOCH: Final[int]
BLOCKAVE: Final[int]
BON: Final[int]
BYTETYPE: Final[int]
CAR: Final[int]
CEA: Final[int]
COD: Final[int]
COE: Final[int]
COMMENT: Final[int]
COMPLEXF: Final[int]
COMPLEXI: Final[int]
CONSERVEFLUX: Final[int]
CONTINUE: Final[int]
COO: Final[int]
COP: Final[int]
CSC: Final[int]
CURRENT: Final[int]
CYP: Final[int]
DISVAR: Final[int]
DOUBLETYPE: Final[int]
EQ: Final[int]
FLOATTYPE: Final[int]
FLOAT: Final[int]
GATTR: Final[int]
GAUSS: Final[int]
GBBUF: Final[int]
GCAP: Final[int]
GE: Final[int]
GEBUF: Final[int]
GENVAR: Final[int]
GFLUSH: Final[int]
GLINE: Final[int]
GLS: Final[int]
GMARK: Final[int]
GMST: Final[int]
GQCH: Final[int]
GSCALES: Final[int]
GT: Final[int]
GTEXT: Final[int]
GTXEXT: Final[int]
HPX: Final[int]
INT: Final[int]
INTTYPE: Final[int]
JD: Final[int]
JEPOCH: Final[int]
LAST: Final[int]
LE: Final[int]
LINEAR: Final[int]
LMST: Final[int]
LOGICAL: Final[int]
LT: Final[int]
MER: Final[int]
MJD: Final[int]
MOL: Final[int]
MXKEYLEN: Final[int]
NCP: Final[int]
NE: Final[int]
NEAREST: Final[int]
NGRFFUN: Final[int]
NOBAD: Final[int]
NOFRAME: Final[int]
NOFWD: Final[int]
NOINV: Final[int]
NOTYPE: Final[int]
NPID: Final[int]
OBJECTTYPE: Final[int]
OR: Final[int]
PAR: Final[int]
PCO: Final[int]
POINTERTYPE: Final[int]
QSC: Final[int]
REBININIT: Final[int]
REBINEND: Final[int]
SFL: Final[int]
SIMPIF: Final[int]
SIMPFI: Final[int]
SIN: Final[int]
SINCSINC: Final[int]
SINCGAUSS: Final[int]
SINCCOS: Final[int]
SINC: Final[int]
SINTTYPE: Final[int]
SOMBCOS: Final[int]
SOMB: Final[int]
STG: Final[int]
STRING: Final[int]
STRINGTYPE: Final[int]
SZP: Final[int]
TAI: Final[int]
TAN: Final[int]
TCB: Final[int]
TCG: Final[int]
TDB: Final[int]
TPN: Final[int]
TSC: Final[int]
TT: Final[int]
TUNULL: Final[int]
UINTERP: Final[int]
UKERN1: Final[int]
UNDEFTYPE: Final[int]
UNDEF: Final[int]
URESAMP1: Final[int]
URESAMP2: Final[int]
URESAMP3: Final[int]
URESAMP4: Final[int]
USEBAD: Final[int]
USEVAR: Final[int]
UT1: Final[int]
UTC: Final[int]
VARWGT: Final[int]
WCSBAD: Final[int]
WCSMX: Final[int]
XMLATTR: Final[int]
XMLBLACK: Final[int]
XMLBAD: Final[int]
XMLCONT: Final[int]
XMLCOM: Final[int]
XMLCHAR: Final[int]
XMLCDATA: Final[int]
XMLDTD: Final[int]
XMLDOC: Final[int]
XMLDEC: Final[int]
XMLELEM: Final[int]
XMLMISC: Final[int]
XMLNAME: Final[int]
XMLOBJECT: Final[int]
XMLPRO: Final[int]
XMLPI: Final[int]
XMLPAR: Final[int]
XMLWHITE: Final[int]
XOR: Final[int]
ZEA: Final[int]
ZPN: Final[int]
STYLE: Final[int]
WIDTH: Final[int]
SIZE: Final[int]
FONT: Final[int]
COLOUR: Final[int]
TEXT: Final[int]
LINE: Final[int]
MARK: Final[int]
NATTR: Final[int]
ESC: Final[int]
MJUST: Final[int]
SCALES: Final[int]
ESPER: Final[int]
ESSUP: Final[int]
ESSUB: Final[int]
ESGAP: Final[int]
ESBAC: Final[int]
ESSIZ: Final[int]
ESWID: Final[int]
ESFON: Final[int]
ESCOL: Final[int]
ESSTY: Final[int]
ESPOP: Final[int]
ESPSH: Final[int]
ESH: Final[int]
ESG: Final[int]


def convex(*args: Any, **kwargs: Any) -> Any: ...
def escapes(newval: int) -> int: ...
def outline(*args: Any, **kwargs: Any) -> Any: ...
def tune(name: str, value: int) -> int: ...
def tunec(name: str, value: str = ...) -> str: ...
def activememory(label: str) -> None: ...
def watchmemory(id: int) -> None: ...
def version() -> int: ...
def get_include() -> str: ...

def __getattr__(name: str) -> Any: ...

class Object(object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    @property
    def Class(self) -> str: ...
    @property
    def ID(self) -> str: ...
    @ID.setter
    def ID(self, value: str) -> None: ...
    @property
    def Ident(self) -> str: ...
    @Ident.setter
    def Ident(self, value: str) -> None: ...
    @property
    def Nobject(self) -> int: ...
    @property
    def ObjSize(self) -> int: ...
    @property
    def RefCount(self) -> int: ...
    @property
    def UseDefs(self) -> bool: ...
    @UseDefs.setter
    def UseDefs(self, value: bool) -> None: ...
    def __deepcopy__(self, memo: Any) -> Object: ...
    def clear(self, attrib: str) -> None: ...
    def copy(self) -> Object: ...
    def get(self, attrib: str) -> str: ...
    def hasattribute(self, attrib: str) -> bool: ...
    def lock(self, wait: int = ...) -> None: ...
    def set(self, settings: str) -> None: ...
    def show(self) -> None: ...
    def same(self, other: Object) -> bool: ...
    def test(self, attrib: str) -> bool: ...
    def unlock(self, report: int = ...) -> None: ...
    def isabox(self, *args: Any, **kwargs: Any) -> bool: ...
    def isachannel(self, *args: Any, **kwargs: Any) -> bool: ...
    def isachebymap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isacircle(self, *args: Any, **kwargs: Any) -> bool: ...
    def isacmpframe(self, *args: Any, **kwargs: Any) -> bool: ...
    def isacmpmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isacmpregion(self, *args: Any, **kwargs: Any) -> bool: ...
    def isadsbspecframe(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaellipse(self, *args: Any, **kwargs: Any) -> bool: ...
    def isafitschan(self, *args: Any, **kwargs: Any) -> bool: ...
    def isafitstable(self, *args: Any, **kwargs: Any) -> bool: ...
    def isafluxframe(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaframe(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaframeset(self, *args: Any, **kwargs: Any) -> bool: ...
    def isagrismmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isainterval(self, *args: Any, **kwargs: Any) -> bool: ...
    def isakeymap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isalutmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isamapping(self, *args: Any, **kwargs: Any) -> bool: ...
    def isamathmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isamatrixmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isamoc(self, *args: Any, **kwargs: Any) -> bool: ...
    def isamocchan(self, *args: Any, **kwargs: Any) -> bool: ...
    def isanormmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isanullregion(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaobject(self, *args: Any, **kwargs: Any) -> bool: ...
    def isapcdmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isapermmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaplot(self, *args: Any, **kwargs: Any) -> bool: ...
    def isapointlist(self, *args: Any, **kwargs: Any) -> bool: ...
    def isapolygon(self, *args: Any, **kwargs: Any) -> bool: ...
    def isapolymap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaprism(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaratemap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaregion(self, *args: Any, **kwargs: Any) -> bool: ...
    def isashiftmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaskyframe(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaslamap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaspecfluxframe(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaspecframe(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaspecmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isasphmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isasplinemap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isastcschan(self, *args: Any, **kwargs: Any) -> bool: ...
    def isatable(self, *args: Any, **kwargs: Any) -> bool: ...
    def isatimeframe(self, *args: Any, **kwargs: Any) -> bool: ...
    def isatimemap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isatranmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaunitmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isaunitnormmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isawcsmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isawinmap(self, *args: Any, **kwargs: Any) -> bool: ...
    def isayamlchan(self, *args: Any, **kwargs: Any) -> bool: ...
    def isazoommap(self, *args: Any, **kwargs: Any) -> bool: ...

class Mapping(Object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def Invert(self) -> int: ...
    @Invert.setter
    def Invert(self, value: int) -> None: ...
    @property
    def IsLinear(self) -> bool: ...
    @property
    def IsSimple(self) -> bool: ...
    @property
    def Nin(self) -> int: ...
    @property
    def Nout(self) -> int: ...
    @property
    def Report(self) -> int: ...
    @Report.setter
    def Report(self, value: int) -> None: ...
    @property
    def TranForward(self) -> bool: ...
    @property
    def TranInverse(self) -> bool: ...
    def decompose(self) -> Any: ...
    def invert(self) -> None: ...
    def mapbox(self, lbnd_in_object: Any, ubnd_in_object: Any, coord_out: int, forward: int = ...) -> Any: ...
    def mapmerge(self, where: int, series: int, maplist_object: Any, invlist_object: Any) -> Any: ...
    def mapsplit(self, in_object: Any) -> Any: ...
    def linearapprox(self, lbnd_object: Any, ubnd_object: Any, tol: float) -> Any: ...
    def quadapprox(self, lbnd_object: Any, ubnd_object: Any, nx: int, ny: int) -> Any: ...
    def rate(self, at_object: Any, ax1: int = ..., ax2: int = ...) -> float: ...
    def rebin(self, *args: Any, **kwargs: Any) -> Any: ...
    def rebinseq(self, *args: Any, **kwargs: Any) -> Any: ...
    def resample(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeregions(self) -> Any: ...
    def simplify(self) -> Any: ...
    def tran(self, in_object: Any, forward: int = ..., out_object: Any = ...) -> Any: ...
    def trangrid(self, lbnd_object: Any, ubnd_object: Any, tol: float = ..., maxpix: int = ..., forward: int = ...) -> Any: ...

class ZoomMap(Mapping):
    def __init__(self, ncoord: int, zoom: float, options: str = ...) -> None: ...
    @property
    def Zoom(self) -> float: ...
    @Zoom.setter
    def Zoom(self, value: float) -> None: ...

class MathMap(Mapping):
    def __init__(self, nin: int, nout: int, fwd_object: Any, inv_object: Any, options: str = ...) -> None: ...
    @property
    def Seed(self) -> int: ...
    @Seed.setter
    def Seed(self, value: int) -> None: ...
    @property
    def SimpFI(self) -> bool: ...
    @SimpFI.setter
    def SimpFI(self, value: bool) -> None: ...
    @property
    def SimpIF(self) -> bool: ...
    @SimpIF.setter
    def SimpIF(self, value: bool) -> None: ...

class SphMap(Mapping):
    def __init__(self, options: str = ...) -> None: ...
    @property
    def UnitRadius(self) -> bool: ...
    @UnitRadius.setter
    def UnitRadius(self, value: bool) -> None: ...
    @property
    def PolarLong(self) -> float: ...
    @PolarLong.setter
    def PolarLong(self, value: float) -> None: ...

class GrismMap(Mapping):
    def __init__(self, options: str = ...) -> None: ...
    @property
    def GrismNR(self) -> float: ...
    @GrismNR.setter
    def GrismNR(self, value: float) -> None: ...
    @property
    def GrismNRP(self) -> float: ...
    @GrismNRP.setter
    def GrismNRP(self, value: float) -> None: ...
    @property
    def GrismWaveR(self) -> float: ...
    @GrismWaveR.setter
    def GrismWaveR(self, value: float) -> None: ...
    @property
    def GrismAlpha(self) -> float: ...
    @GrismAlpha.setter
    def GrismAlpha(self, value: float) -> None: ...
    @property
    def GrismG(self) -> float: ...
    @GrismG.setter
    def GrismG(self, value: float) -> None: ...
    @property
    def GrismM(self) -> int: ...
    @GrismM.setter
    def GrismM(self, value: int) -> None: ...
    @property
    def GrismEps(self) -> float: ...
    @GrismEps.setter
    def GrismEps(self, value: float) -> None: ...
    @property
    def GrismTheta(self) -> float: ...
    @GrismTheta.setter
    def GrismTheta(self, value: float) -> None: ...

class PcdMap(Mapping):
    def __init__(self, disco: float, pcdcen_object: Any, options: str = ...) -> None: ...
    @property
    def Disco(self) -> float: ...
    @Disco.setter
    def Disco(self, value: float) -> None: ...

class WcsMap(Mapping):
    def __init__(self, ncoord: int = ..., type: int = ..., lonax: int = ..., latax: int = ..., options: str = ...) -> None: ...
    @property
    def WcsType(self) -> int: ...
    @property
    def NatLon(self) -> float: ...
    @property
    def NatLat(self) -> float: ...

class UnitMap(Mapping):
    def __init__(self, ncoord: int, options: str = ...) -> None: ...

class TimeMap(Mapping):
    def __init__(self, flags: int = ..., options: str = ...) -> None: ...
    def timeadd(self, cvt: str, astargs_object: Any) -> None: ...

class SplineMap(Mapping):
    def __init__(self, kx: int, ky: int, nx: int, ny: int, tx_object: Any, ty_object: Any, cu_object: Any, cv_object: Any, options: str = ...) -> None: ...
    @property
    def InvNiter(self) -> int: ...
    @InvNiter.setter
    def InvNiter(self, value: int) -> None: ...
    @property
    def OutUnit(self) -> bool: ...
    @OutUnit.setter
    def OutUnit(self, value: bool) -> None: ...
    @property
    def InvTol(self) -> float: ...
    @InvTol.setter
    def InvTol(self, value: float) -> None: ...
    @property
    def SplineKx(self) -> int: ...
    @property
    def SplineKy(self) -> int: ...
    @property
    def SplineNx(self) -> int: ...
    @property
    def SplineNy(self) -> int: ...

class RateMap(Mapping):
    def __init__(self, other: Mapping, ax1: int = ..., ax2: int = ..., options: str = ...) -> None: ...

class CmpMap(Mapping):
    def __init__(self, other: Mapping, another: Mapping, series: int = ..., options: str = ...) -> None: ...

class TranMap(Mapping):
    def __init__(self, other: Mapping, another: Mapping, options: str = ...) -> None: ...

class NormMap(Mapping):
    def __init__(self, other: Frame, options: str = ...) -> None: ...

class PermMap(Mapping):
    def __init__(self, inperm_object: Any, outperm_object: Any, constant_object: Any = ..., options: str = ...) -> None: ...

class ShiftMap(Mapping):
    def __init__(self, shift_object: Any, options: str = ...) -> None: ...

class UnitNormMap(Mapping):
    def __init__(self, centre_object: Any, options: str = ...) -> None: ...

class LutMap(Mapping):
    def __init__(self, lut_object: Any, start: float = ..., inc: float = ..., options: str = ...) -> None: ...

class WinMap(Mapping):
    def __init__(self, ina_object: Any, inb_object: Any, outa_object: Any, outb_object: Any, options: str = ...) -> None: ...

class MatrixMap(Mapping):
    def __init__(self, matrix_object: Any, options: str = ...) -> None: ...

class PolyMap(Mapping):
    def __init__(self, fcoeff_object: Any, icoeff_object: Any = ..., options: str = ...) -> None: ...
    @property
    def IterInverse(self) -> bool: ...
    @IterInverse.setter
    def IterInverse(self, value: bool) -> None: ...
    @property
    def NiterInverse(self) -> int: ...
    @NiterInverse.setter
    def NiterInverse(self, value: int) -> None: ...
    @property
    def TolInverse(self) -> float: ...
    @TolInverse.setter
    def TolInverse(self, value: float) -> None: ...
    def polytran(self, forward: int, acc: float, maxacc: float, maxorder: int, lbnd_object: Any, ubnd_object: Any) -> Any: ...

class ChebyMap(PolyMap):
    def __init__(self, fcoeff_object: Any, lbnd_f_object: Any, ubnd_f_object: Any, icoeff_object: Any = ..., lbnd_i_object: Any = ..., ubnd_i_object: Any = ..., options: str = ...) -> None: ...

class Frame(Mapping):
    def __init__(self, naxes: int, options: str = ...) -> None: ...
    @property
    def Naxes(self) -> int: ...
    @property
    def AlignSystem(self) -> str: ...
    @AlignSystem.setter
    def AlignSystem(self, value: str) -> None: ...
    @property
    def Domain(self) -> str: ...
    @Domain.setter
    def Domain(self, value: str) -> None: ...
    @property
    def System(self) -> str: ...
    @System.setter
    def System(self, value: str) -> None: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> None: ...
    @property
    def Dut1(self) -> float: ...
    @Dut1.setter
    def Dut1(self, value: float) -> None: ...
    @property
    def Epoch(self) -> float: ...
    @Epoch.setter
    def Epoch(self, value: float) -> None: ...
    @property
    def ObsAlt(self) -> float: ...
    @ObsAlt.setter
    def ObsAlt(self, value: float) -> None: ...
    @property
    def ObsLon(self) -> float: ...
    @ObsLon.setter
    def ObsLon(self, value: float) -> None: ...
    @property
    def ObsLat(self) -> float: ...
    @ObsLat.setter
    def ObsLat(self, value: float) -> None: ...
    @property
    def MaxAxes(self) -> int: ...
    @MaxAxes.setter
    def MaxAxes(self, value: int) -> None: ...
    @property
    def MinAxes(self) -> int: ...
    @MinAxes.setter
    def MinAxes(self, value: int) -> None: ...
    @property
    def MatchEnd(self) -> bool: ...
    @MatchEnd.setter
    def MatchEnd(self, value: bool) -> None: ...
    @property
    def Permute(self) -> bool: ...
    @Permute.setter
    def Permute(self, value: bool) -> None: ...
    @property
    def PreserveAxes(self) -> bool: ...
    @PreserveAxes.setter
    def PreserveAxes(self, value: bool) -> None: ...
    def angle(self, a_object: Any, b_object: Any, c_object: Any) -> float: ...
    def axangle(self, a_object: Any, b_object: Any, axis: int) -> float: ...
    def axdistance(self, axis: int, v1: float, v2: float) -> float: ...
    def axoffset(self, axis: int, v1: float, dist: float) -> float: ...
    def convert(self, other: Frame, domainlist: str = ...) -> Any: ...
    def distance(self, point1_object: Any, point2_object: Any) -> float: ...
    def findframe(self, other: Frame, domainlist: str = ...) -> Any: ...
    def format(self, axis: int, value: float) -> str: ...
    def intersect(self, a1_object: Any, a2_object: Any, b1_object: Any, b2_object: Any) -> Any: ...
    def matchaxes(self, other: Frame) -> Any: ...
    def norm(self, value_object: Any) -> Any: ...
    def normpoints(self, in_object: Any, contig: int = ..., out_object: Any = ...) -> Any: ...
    def offset(self, point1_object: Any, point2_object: Any, offset: float) -> Any: ...
    def offset2(self, point1_object: Any, angle: float, offset: float) -> Any: ...
    def permaxes(self, perm_object: Any) -> None: ...
    def pickaxes(self, axes_object: Any) -> Any: ...
    def resolve(self, point1_object: Any, point2_object: Any, point3_object: Any) -> Any: ...
    def unformat(self, axis: int, string: str) -> Any: ...

class FrameSet(Frame):
    def __init__(self, other: Frame, options: str = ...) -> None: ...
    @property
    def Base(self) -> int: ...
    @Base.setter
    def Base(self, value: int) -> None: ...
    @property
    def Current(self) -> int: ...
    @Current.setter
    def Current(self, value: int) -> None: ...
    @property
    def Nframe(self) -> int: ...
    @Nframe.setter
    def Nframe(self, value: int) -> None: ...
    def addframe(self, iframe: int, other: Mapping, another: Frame) -> None: ...
    def getframe(self, iframe: int = ...) -> Any: ...
    def getmapping(self, iframe1: int = ..., iframe2: int = ...) -> Any: ...
    def remapframe(self, iframe: int, other: Mapping) -> None: ...
    def removeframe(self, iframe: int = ...) -> None: ...
    def getnode(self, inode: int) -> Any: ...

class Plot(FrameSet):
    def __init__(self, frame: Any, gbox_object: Any, bbox_object: Any, grf_object: Any, options: str = ...) -> None: ...
    @property
    def Abbrev(self) -> bool: ...
    @Abbrev.setter
    def Abbrev(self, value: bool) -> None: ...
    @property
    def Border(self) -> bool: ...
    @Border.setter
    def Border(self, value: bool) -> None: ...
    @property
    def Clip(self) -> int: ...
    @Clip.setter
    def Clip(self, value: int) -> None: ...
    @property
    def ClipOp(self) -> bool: ...
    @ClipOp.setter
    def ClipOp(self, value: bool) -> None: ...
    @property
    def DrawTitle(self) -> bool: ...
    @DrawTitle.setter
    def DrawTitle(self, value: bool) -> None: ...
    @property
    def Escape(self) -> bool: ...
    @Escape.setter
    def Escape(self, value: bool) -> None: ...
    @property
    def Grid(self) -> bool: ...
    @Grid.setter
    def Grid(self, value: bool) -> None: ...
    @property
    def Invisible(self) -> bool: ...
    @Invisible.setter
    def Invisible(self, value: bool) -> None: ...
    @property
    def Labelling(self) -> str: ...
    @Labelling.setter
    def Labelling(self, value: str) -> None: ...
    @property
    def TickAll(self) -> bool: ...
    @TickAll.setter
    def TickAll(self, value: bool) -> None: ...
    @property
    def ForceExterior(self) -> bool: ...
    @ForceExterior.setter
    def ForceExterior(self, value: bool) -> None: ...
    @property
    def TitleGap(self) -> float: ...
    @TitleGap.setter
    def TitleGap(self, value: float) -> None: ...
    @property
    def Tol(self) -> float: ...
    @Tol.setter
    def Tol(self, value: float) -> None: ...
    def bbuf(self) -> Any: ...
    def border(self) -> Any: ...
    def boundingbox(self) -> Any: ...
    def clip(self, iframe: int, lbnd_object: Any, ubnd_object: Any) -> Any: ...
    def curve(self, start_object: Any, finish_object: Any) -> Any: ...
    def ebuf(self) -> Any: ...
    def gencurve(self, map: Mapping) -> Any: ...
    def grid(self) -> Any: ...
    def gridline(self, axis: int, start_object: Any, length: float) -> Any: ...
    def mark(self, in_object: Any, type: int = ...) -> Any: ...
    def polycurve(self, in_object: Any) -> Any: ...
    def regionoutline(self, other: Region) -> Any: ...
    def text(self, text_object: Any, pos_object: Any, up_object: Any, just_object: Any) -> Any: ...

class CmpFrame(Frame):
    def __init__(self, other: Frame, another: Frame, options: str = ...) -> None: ...

class SpecFrame(Frame):
    def __init__(self, options: str = ...) -> None: ...
    @property
    def AlignSpecOffset(self) -> bool: ...
    @AlignSpecOffset.setter
    def AlignSpecOffset(self, value: bool) -> None: ...
    @property
    def AlignStdOfRest(self) -> str: ...
    @AlignStdOfRest.setter
    def AlignStdOfRest(self, value: str) -> None: ...
    @property
    def RefDec(self) -> str: ...
    @RefDec.setter
    def RefDec(self, value: str) -> None: ...
    @property
    def RefRA(self) -> str: ...
    @RefRA.setter
    def RefRA(self, value: str) -> None: ...
    @property
    def RestFreq(self) -> float: ...
    @RestFreq.setter
    def RestFreq(self, value: float) -> None: ...
    @property
    def SourceSys(self) -> str: ...
    @SourceSys.setter
    def SourceSys(self, value: str) -> None: ...
    @property
    def SourceVel(self) -> float: ...
    @SourceVel.setter
    def SourceVel(self, value: float) -> None: ...
    @property
    def SourceVRF(self) -> str: ...
    @SourceVRF.setter
    def SourceVRF(self, value: str) -> None: ...
    @property
    def SpecOrigin(self) -> float: ...
    @SpecOrigin.setter
    def SpecOrigin(self, value: float) -> None: ...
    @property
    def StdOfRest(self) -> str: ...
    @StdOfRest.setter
    def StdOfRest(self, value: str) -> None: ...
    def setrefpos(self, other: SkyFrame, lon: float, lat: float) -> None: ...
    def getrefpos(self, other: SkyFrame) -> Any: ...

class SlaMap(Mapping):
    def __init__(self, flags: int = ..., options: str = ...) -> None: ...

class SpecMap(Mapping):
    def __init__(self, nin: int, flags: int = ..., options: str = ...) -> None: ...

class DSBSpecFrame(SpecFrame):
    def __init__(self, options: str = ...) -> None: ...
    @property
    def AlignSideBand(self) -> bool: ...
    @AlignSideBand.setter
    def AlignSideBand(self, value: bool) -> None: ...
    @property
    def DSBCentre(self) -> float: ...
    @DSBCentre.setter
    def DSBCentre(self, value: float) -> None: ...
    @property
    def IF(self) -> float: ...
    @IF.setter
    def IF(self, value: float) -> None: ...
    @property
    def ImagFreq(self) -> float: ...
    @ImagFreq.setter
    def ImagFreq(self, value: float) -> None: ...
    @property
    def SideBand(self) -> str: ...
    @SideBand.setter
    def SideBand(self, value: str) -> None: ...

class SkyFrame(Frame):
    def __init__(self, options: str = ...) -> None: ...
    @property
    def Projection(self) -> str: ...
    @Projection.setter
    def Projection(self, value: str) -> None: ...
    @property
    def SkyRefIs(self) -> str: ...
    @SkyRefIs.setter
    def SkyRefIs(self, value: str) -> None: ...
    @property
    def Equinox(self) -> float: ...
    @Equinox.setter
    def Equinox(self, value: float) -> None: ...
    @property
    def LatAxis(self) -> int: ...
    @LatAxis.setter
    def LatAxis(self, value: int) -> None: ...
    @property
    def LonAxis(self) -> int: ...
    @LonAxis.setter
    def LonAxis(self, value: int) -> None: ...
    @property
    def AlignOffset(self) -> bool: ...
    @AlignOffset.setter
    def AlignOffset(self, value: bool) -> None: ...
    @property
    def NegLon(self) -> bool: ...
    @NegLon.setter
    def NegLon(self, value: bool) -> None: ...
    def skyoffsetmap(self) -> Any: ...

class TimeFrame(Frame):
    def __init__(self, options: str = ...) -> None: ...
    @property
    def AlignTimeScale(self) -> str: ...
    @AlignTimeScale.setter
    def AlignTimeScale(self, value: str) -> None: ...
    @property
    def LTOffset(self) -> float: ...
    @LTOffset.setter
    def LTOffset(self, value: float) -> None: ...
    @property
    def TimeOrigin(self) -> float: ...
    @TimeOrigin.setter
    def TimeOrigin(self, value: float) -> None: ...
    @property
    def TimeScale(self) -> str: ...
    @TimeScale.setter
    def TimeScale(self, value: str) -> None: ...
    def currenttime(self) -> float: ...

class FluxFrame(Frame):
    def __init__(self, specval: float = ..., other: SpecFrame = ..., options: str = ...) -> None: ...
    @property
    def SpecVal(self) -> float: ...
    @SpecVal.setter
    def SpecVal(self, value: float) -> None: ...

class SpecFluxFrame(CmpFrame):
    def __init__(self, other: SpecFrame, another: FluxFrame, options: str = ...) -> None: ...

class Region(Frame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def Adaptive(self) -> bool: ...
    @Adaptive.setter
    def Adaptive(self, value: bool) -> None: ...
    @property
    def Negated(self) -> bool: ...
    @Negated.setter
    def Negated(self, value: bool) -> None: ...
    @property
    def Closed(self) -> bool: ...
    @Closed.setter
    def Closed(self, value: bool) -> None: ...
    @property
    def MeshSize(self) -> int: ...
    @MeshSize.setter
    def MeshSize(self, value: int) -> None: ...
    @property
    def FillFactor(self) -> float: ...
    @FillFactor.setter
    def FillFactor(self, value: float) -> None: ...
    @property
    def Bounded(self) -> bool: ...
    def getregionframe(self) -> Any: ...
    def getregionbounds(self) -> Any: ...
    def getregiondisc(self) -> Any: ...
    def mapregion(self, other: Mapping, another: Frame) -> Any: ...
    def negate(self) -> None: ...
    def overlap(self, other: Region) -> Any: ...
    def getregionpoints(self, *args: Any, **kwargs: Any) -> Any: ...
    def getregionmesh(self, surface: int = ...) -> Any: ...
    def mask(self, *args: Any, **kwargs: Any) -> Any: ...
    def pointinregion(self, point_object: Any) -> bool: ...

class Box(Region):
    def __init__(self, other: Frame, form: int, point1_object: Any, point2_object: Any, another: Region = ..., options: str = ...) -> None: ...

class Circle(Region):
    def __init__(self, other: Frame, form: int, centre_object: Any, point_object: Any, another: Region = ..., options: str = ...) -> None: ...
    def circlepars(self, *args: Any, **kwargs: Any) -> Any: ...

class PointList(Region):
    def __init__(self, other: Frame, points_object: Any, another: Region = ..., options: str = ...) -> None: ...
    @property
    def ListSize(self) -> int: ...

class Polygon(Region):
    def __init__(self, other: Frame, points_object: Any, another: Region = ..., options: str = ...) -> None: ...
    def downsize(self, maxerr: float, maxvert: int) -> Any: ...

class Ellipse(Region):
    def __init__(self, other: Frame, form: int, centre_object: Any, point1_object: Any, point2_object: Any, another: Region = ..., options: str = ...) -> None: ...
    def ellipsepars(self, *args: Any, **kwargs: Any) -> Any: ...

class Interval(Region):
    def __init__(self, other: Frame, lbnd_object: Any, ubnd_object: Any, another: Region = ..., options: str = ...) -> None: ...

class Moc(Region):
    def __init__(self, options: str = ...) -> None: ...
    @property
    def MaxOrder(self) -> int: ...
    @MaxOrder.setter
    def MaxOrder(self, value: int) -> None: ...
    @property
    def MinOrder(self) -> int: ...
    @MinOrder.setter
    def MinOrder(self, value: int) -> None: ...
    @property
    def MaxRes(self) -> float: ...
    @MaxRes.setter
    def MaxRes(self, value: float) -> None: ...
    @property
    def MinRes(self) -> float: ...
    @MinRes.setter
    def MinRes(self, value: float) -> None: ...
    @property
    def MocType(self) -> int: ...
    @property
    def MocLength(self) -> int: ...
    @property
    def MocArea(self) -> float: ...
    def addcell(self, order: int, npix: int, cmode: int = ...) -> None: ...
    def addmocdata(self, data_object: Any, cmode: int = ..., negate: int = ..., maxorder: int = ...) -> None: ...
    def addmocstring(self, string: str, json: int = ..., cmode: int = ..., negate: int = ...) -> Any: ...
    def addpixelmask(self, *args: Any, **kwargs: Any) -> None: ...
    def addregion(self, other: Region, cmode: int = ...) -> None: ...
    def getcell(self, icell: int) -> Any: ...
    def getmocdata(self, *args: Any, **kwargs: Any) -> Any: ...
    def getmocstring(self, json: int = ...) -> str: ...
    def getmocheader(self, *args: Any, **kwargs: Any) -> Any: ...
    def testcell(self, order: int, npix: int, parent: int) -> bool: ...

class NullRegion(Region):
    def __init__(self, other: Frame, another: Region = ..., options: str = ...) -> None: ...

class CmpRegion(Region):
    def __init__(self, other: Region, another: Region, oper: int = ..., options: str = ...) -> None: ...

class Prism(Region):
    def __init__(self, other: Region, another: Region, options: str = ...) -> None: ...

class Channel(Object):
    def __init__(self, source: Any = ..., sink: Any = ..., options: str = ...) -> None: ...
    @property
    def SourceFile(self) -> str: ...
    @SourceFile.setter
    def SourceFile(self, value: str) -> None: ...
    @property
    def SinkFile(self) -> str: ...
    @SinkFile.setter
    def SinkFile(self, value: str) -> None: ...
    @property
    def Comment(self) -> bool: ...
    @Comment.setter
    def Comment(self, value: bool) -> None: ...
    @property
    def Full(self) -> int: ...
    @Full.setter
    def Full(self, value: int) -> None: ...
    @property
    def Indent(self) -> int: ...
    @Indent.setter
    def Indent(self, value: int) -> None: ...
    @property
    def ReportLevel(self) -> int: ...
    @ReportLevel.setter
    def ReportLevel(self, value: int) -> None: ...
    @property
    def Skip(self) -> bool: ...
    @Skip.setter
    def Skip(self, value: bool) -> None: ...
    @property
    def Strict(self) -> bool: ...
    @Strict.setter
    def Strict(self, value: bool) -> None: ...
    def warnings(self) -> Any: ...
    def read(self, rewind: int = ...) -> Any: ...
    def write(self, other: Object) -> int: ...

class FitsChan(Channel):
    def __init__(self, source: Any = ..., sink: Any = ..., options: str = ...) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: str) -> Any: ...
    @property
    def AllWarnings(self) -> str: ...
    @property
    def Card(self) -> int: ...
    @Card.setter
    def Card(self, value: int) -> None: ...
    @property
    def CarLin(self) -> bool: ...
    @CarLin.setter
    def CarLin(self, value: bool) -> None: ...
    @property
    def CDMatrix(self) -> bool: ...
    @CDMatrix.setter
    def CDMatrix(self, value: bool) -> None: ...
    @property
    def Clean(self) -> bool: ...
    @Clean.setter
    def Clean(self, value: bool) -> None: ...
    @property
    def DefB1950(self) -> bool: ...
    @DefB1950.setter
    def DefB1950(self, value: bool) -> None: ...
    @property
    def Encoding(self) -> str: ...
    @Encoding.setter
    def Encoding(self, value: str) -> None: ...
    @property
    def FitsDigits(self) -> int: ...
    @FitsDigits.setter
    def FitsDigits(self, value: int) -> None: ...
    @property
    def Iwc(self) -> bool: ...
    @Iwc.setter
    def Iwc(self, value: bool) -> None: ...
    @property
    def Ncard(self) -> int: ...
    @property
    def Nkey(self) -> int: ...
    @property
    def TabOK(self) -> bool: ...
    @TabOK.setter
    def TabOK(self, value: bool) -> None: ...
    @property
    def PolyTan(self) -> int: ...
    @PolyTan.setter
    def PolyTan(self, value: int) -> None: ...
    @property
    def Warnings(self) -> str: ...
    @Warnings.setter
    def Warnings(self, value: str) -> None: ...
    def delfits(self) -> None: ...
    def emptyfits(self) -> None: ...
    def findfits(self, name: str, inc: int = ...) -> Any: ...
    def getfitsCF(self, *args: Any, **kwargs: Any) -> Any: ...
    def getfitsCI(self, *args: Any, **kwargs: Any) -> Any: ...
    def getfitsF(self, *args: Any, **kwargs: Any) -> Any: ...
    def getfitsI(self, *args: Any, **kwargs: Any) -> Any: ...
    def getfitsL(self, *args: Any, **kwargs: Any) -> Any: ...
    def getfitsS(self, *args: Any, **kwargs: Any) -> Any: ...
    def getfitsCN(self, *args: Any, **kwargs: Any) -> Any: ...
    def gettables(self) -> Any: ...
    def keys(self) -> Any: ...
    def purgewcs(self) -> None: ...
    def putcards(self, cards: str) -> None: ...
    def putfits(self, card: str, overwrite: int = ...) -> None: ...
    def puttable(self, table: FitsTable, extnam: str) -> None: ...
    def puttables(self, tables: KeyMap) -> None: ...
    def readfits(self) -> None: ...
    def retainfits(self) -> None: ...
    def removetables(self, key: str) -> None: ...
    def setfitsCF(self, *args: Any, **kwargs: Any) -> Any: ...
    def setfitsCI(self, *args: Any, **kwargs: Any) -> Any: ...
    def setfitsF(self, *args: Any, **kwargs: Any) -> Any: ...
    def setfitsI(self, *args: Any, **kwargs: Any) -> Any: ...
    def setfitsL(self, *args: Any, **kwargs: Any) -> Any: ...
    def setfitsS(self, *args: Any, **kwargs: Any) -> Any: ...
    def setfitsCN(self, *args: Any, **kwargs: Any) -> Any: ...
    def testfits(self, name: str) -> Any: ...
    def tablesource(self, tabsource: Any) -> None: ...
    def writefits(self) -> None: ...

class StcsChan(Channel):
    def __init__(self, source: Any = ..., sink: Any = ..., options: str = ...) -> None: ...
    @property
    def StcsArea(self) -> bool: ...
    @StcsArea.setter
    def StcsArea(self, value: bool) -> None: ...
    @property
    def StcsCoords(self) -> bool: ...
    @StcsCoords.setter
    def StcsCoords(self, value: bool) -> None: ...
    @property
    def StcsProps(self) -> bool: ...
    @StcsProps.setter
    def StcsProps(self, value: bool) -> None: ...
    @property
    def StcsLength(self) -> int: ...
    @StcsLength.setter
    def StcsLength(self, value: int) -> None: ...

class YamlChan(Channel):
    def __init__(self, source: Any = ..., sink: Any = ..., options: str = ...) -> None: ...
    @property
    def VerboseRead(self) -> bool: ...
    @VerboseRead.setter
    def VerboseRead(self, value: bool) -> None: ...
    @property
    def PreserveName(self) -> bool: ...
    @PreserveName.setter
    def PreserveName(self, value: bool) -> None: ...
    @property
    def YamlEncoding(self) -> str: ...
    @YamlEncoding.setter
    def YamlEncoding(self, value: str) -> None: ...

class MocChan(Channel):
    def __init__(self, source: Any = ..., sink: Any = ..., options: str = ...) -> None: ...
    @property
    def MocFormat(self) -> bool: ...
    @MocFormat.setter
    def MocFormat(self, value: bool) -> None: ...
    @property
    def MocLineLen(self) -> int: ...
    @MocLineLen.setter
    def MocLineLen(self, value: int) -> None: ...

class KeyMap(Object):
    def __init__(self, options: str = ...) -> None: ...
    @property
    def KeyCase(self) -> bool: ...
    @KeyCase.setter
    def KeyCase(self, value: bool) -> None: ...
    @property
    def SizeGuess(self) -> int: ...
    @SizeGuess.setter
    def SizeGuess(self, value: int) -> None: ...
    @property
    def KeyError(self) -> bool: ...
    @KeyError.setter
    def KeyError(self, value: bool) -> None: ...
    @property
    def MapLocked(self) -> bool: ...
    @MapLocked.setter
    def MapLocked(self, value: bool) -> None: ...
    @property
    def SortBy(self) -> str: ...
    @SortBy.setter
    def SortBy(self, value: str) -> None: ...
    def keys(self) -> list[str]: ...

class Table(KeyMap):
    def __init__(self, options: str = ...) -> None: ...
    @property
    def Ncolumn(self) -> int: ...
    @property
    def Nrow(self) -> int: ...
    @property
    def Nparameter(self) -> int: ...
    def addcolumn(self, name: str, type: int, dims_object: Any = ..., unit: str = ...) -> None: ...
    def addparameter(self, name: str) -> None: ...
    def columnname(self, index: int) -> str: ...
    def columnshape(self, column: str) -> Any: ...
    def hascolumn(self, column: str) -> bool: ...
    def hasparameter(self, parameter: str) -> bool: ...
    def parametername(self, index: int) -> str: ...
    def purgerows(self) -> None: ...
    def removecolumn(self, column: str) -> None: ...
    def removeparameter(self, name: str) -> None: ...
    def removerow(self, index: int) -> None: ...
    def columnlenc(self, column: str) -> int: ...
    def columnlength(self, column: str) -> int: ...
    def columnndim(self, column: str) -> int: ...
    def columntype(self, column: str) -> int: ...
    def columnunit(self, column: str) -> str: ...

class FitsTable(Table):
    def __init__(self, header: FitsChan = ..., options: str = ...) -> None: ...
    def columnnull(self, column: str, set: int = ...) -> Any: ...
    def columnsize(self, column: str) -> int: ...
    def gettableheader(self, *args: Any, **kwargs: Any) -> Any: ...
    def puttableheader(self, header: FitsChan) -> None: ...
